Repository humpexon/cipher-programs, pull requests merged in 2022-10, with the labels that each got.

#1 Create caesar cipher.c
  caesar cipher/caesar cipher.c
Labels: hacktoberfest

#2 Create caesar cipher.cpp
  caesar cipher/caesar cipher.cpp
Labels: hacktoberfest, hacktoberfest2022, hactoberfest-accepted

#7 Update caesar cipher.java
  caesar cipher/caesar cipher.java
Labels: hacktoberfest, hacktoberfest2022, hactoberfest-accepted

#6 Update caesar cipher.java
  caesar cipher/caesar cipher.java
Labels: invalid, hacktoberfest, hacktoberfest2022, hactoberfest-accepted, invalid.

#8 Create Monoalphabetic.c
  Monoalphabetic Cipher/Monoalphabetic.c
Labels: hacktoberfest, hacktoberfest2022, hactoberfest-accepted

#9 Create Monoalphabetic.cpp
  Monoalphabetic Cipher/Monoalphabetic.cpp
Labels: hacktoberfest, hacktoberfest2022, hactoberfest-accepted

#10 Create Monoalphabetic.java
  Monoalphabetic Cipher/Monoalphabetic.java
Labels: hacktoberfest, hacktoberfest2022, hactoberfest-accepted

#11 create monoalphabetic.py
  Monoalphabetic Cipher/Monoalphabetic.py
Labels: hacktoberfest, hacktoberfest2022, hactoberfest-accepted
